require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FavorsController do

  # This should return the minimal set of attributes required to create a valid
  # Favor. As you add validations to Favor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "address" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FavorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all favors as @favors" do
      favor = Favor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:favors).should eq([favor])
    end
  end

  describe "GET show" do
    it "assigns the requested favor as @favor" do
      favor = Favor.create! valid_attributes
      get :show, {:id => favor.to_param}, valid_session
      assigns(:favor).should eq(favor)
    end
  end

  describe "GET new" do
    it "assigns a new favor as @favor" do
      get :new, {}, valid_session
      assigns(:favor).should be_a_new(Favor)
    end
  end

  describe "GET edit" do
    it "assigns the requested favor as @favor" do
      favor = Favor.create! valid_attributes
      get :edit, {:id => favor.to_param}, valid_session
      assigns(:favor).should eq(favor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Favor" do
        expect {
          post :create, {:favor => valid_attributes}, valid_session
        }.to change(Favor, :count).by(1)
      end

      it "assigns a newly created favor as @favor" do
        post :create, {:favor => valid_attributes}, valid_session
        assigns(:favor).should be_a(Favor)
        assigns(:favor).should be_persisted
      end

      it "redirects to the created favor" do
        post :create, {:favor => valid_attributes}, valid_session
        response.should redirect_to(Favor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved favor as @favor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Favor.any_instance.stub(:save).and_return(false)
        post :create, {:favor => { "address" => "invalid value" }}, valid_session
        assigns(:favor).should be_a_new(Favor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Favor.any_instance.stub(:save).and_return(false)
        post :create, {:favor => { "address" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested favor" do
        favor = Favor.create! valid_attributes
        # Assuming there are no other favors in the database, this
        # specifies that the Favor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Favor.any_instance.should_receive(:update).with({ "address" => "MyString" })
        put :update, {:id => favor.to_param, :favor => { "address" => "MyString" }}, valid_session
      end

      it "assigns the requested favor as @favor" do
        favor = Favor.create! valid_attributes
        put :update, {:id => favor.to_param, :favor => valid_attributes}, valid_session
        assigns(:favor).should eq(favor)
      end

      it "redirects to the favor" do
        favor = Favor.create! valid_attributes
        put :update, {:id => favor.to_param, :favor => valid_attributes}, valid_session
        response.should redirect_to(favor)
      end
    end

    describe "with invalid params" do
      it "assigns the favor as @favor" do
        favor = Favor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Favor.any_instance.stub(:save).and_return(false)
        put :update, {:id => favor.to_param, :favor => { "address" => "invalid value" }}, valid_session
        assigns(:favor).should eq(favor)
      end

      it "re-renders the 'edit' template" do
        favor = Favor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Favor.any_instance.stub(:save).and_return(false)
        put :update, {:id => favor.to_param, :favor => { "address" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested favor" do
      favor = Favor.create! valid_attributes
      expect {
        delete :destroy, {:id => favor.to_param}, valid_session
      }.to change(Favor, :count).by(-1)
    end

    it "redirects to the favors list" do
      favor = Favor.create! valid_attributes
      delete :destroy, {:id => favor.to_param}, valid_session
      response.should redirect_to(favors_url)
    end
  end

end
